version: '3.4'
services:
    flask-server:
        image: my-custom-flask-image
        build:
            context: .
            dockerfile: flask-dockerfile
        ports:
            - 5055:5000
        volumes:
            - .:/app:cached
        # command: python microservice/main.py run -h 0.0.0.0
